name: CI -> Deploy to My website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.GIT_CPANEL_SERVER }}
          username: ${{ secrets.GIT_CPANEL_USER }}
          password: ${{ secrets.GIT_CPANEL_PWD }}
